#!/usr/bin/env bash
set -euo pipefail

INSTALLER_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=resolve-source-root.sh
source "${INSTALLER_ROOT}/resolve-source-root.sh"

SOURCE_ROOT="${SOURCE_ROOT:-$(resolve_source_root "${INSTALLER_ROOT}")}"
OUTPUT_DIR="${OUTPUT_DIR:-${INSTALLER_ROOT}/output/app}"
BUILD_DIR="${INSTALLER_ROOT}/build/pyinstaller"
DIST_DIR="${INSTALLER_ROOT}/dist"

if [[ -x "${SOURCE_ROOT}/.venv/bin/python" ]]; then
  PYTHON="${SOURCE_ROOT}/.venv/bin/python"
else
  PYTHON="${PYTHON:-python3}"
fi

if [[ "$(uname -s)" != "Linux" ]]; then
  echo "ERROR: Linux build must run on Linux." >&2
  exit 1
fi

if [[ ! -f "${SOURCE_ROOT}/pipeline_orchestrator_gui.py" ]]; then
  echo "ERROR: Source not found: ${SOURCE_ROOT}" >&2
  exit 1
fi

echo "==> Python: ${PYTHON}"
echo "==> Source: ${SOURCE_ROOT}"

"${PYTHON}" -m pip install --upgrade pip pyinstaller

rm -rf "${BUILD_DIR}" "${DIST_DIR}"
mkdir -p "${BUILD_DIR}"

LAUNCHER="${INSTALLER_ROOT}/launcher_orchestrator.py"
SPEC_BASE="${INSTALLER_ROOT}/soundspectranalyse_orchestrator.spec"
PATCHED="${BUILD_DIR}/soundspectranalyse_orchestrator.patched.spec"

{
  echo "# Auto-generated by build-pyinstaller.sh"
  echo "SOURCE_ROOT = r'${SOURCE_ROOT//\'/\\\'}'"
  echo "LAUNCHER_SCRIPT = r'${LAUNCHER//\'/\\\'}'"
  cat "${SPEC_BASE}"
} > "${PATCHED}"

(cd "${INSTALLER_ROOT}" && "${PYTHON}" -m PyInstaller \
  --noconfirm --clean \
  --distpath "${DIST_DIR}" \
  --workpath "${BUILD_DIR}" \
  "${PATCHED}")

BUILT="${DIST_DIR}/SoundSpectrAnalyse"
if [[ ! -d "${BUILT}" ]]; then
  echo "ERROR: Expected ${BUILT}" >&2
  exit 1
fi

rm -rf "${OUTPUT_DIR}"
mkdir -p "$(dirname "${OUTPUT_DIR}")"
cp -R "${BUILT}" "${OUTPUT_DIR}/"

cat > "${OUTPUT_DIR}/README.txt" <<'EOF'
SoundSpectrAnalyse (Linux portable build)
=========================================

Run: ./SoundSpectrAnalyse-Orchestrator

Or: ./install-soundspectranalyse.sh for menu shortcut (~/.local)

Optional: install ffmpeg for some audio formats.

https://github.com/LuisMRaimundo/SoundSpectrAnalyse
EOF

cp -f "${INSTALLER_ROOT}/install-soundspectranalyse.sh" "${OUTPUT_DIR}/"
chmod +x "${OUTPUT_DIR}/install-soundspectranalyse.sh" \
  "${OUTPUT_DIR}/SoundSpectrAnalyse-Orchestrator" 2>/dev/null || true

echo ""
echo "SUCCESS: ${OUTPUT_DIR}/"
