#Requires -Version 5.1
<#
.SYNOPSIS
  Build a standalone SoundSpectrAnalyse folder (no Python required on target PC).
#>
[CmdletBinding()]
param(
    [string]$SourceRoot = "",
    [string]$PythonExe = "",
    [string]$OutputDir = ""
)

$ErrorActionPreference = "Stop"
$InstallerRoot = if ($PSScriptRoot) { $PSScriptRoot } else { Split-Path -Parent $MyInvocation.MyCommand.Path }
. (Join-Path $InstallerRoot "Resolve-SourceRoot.ps1")

if (-not $SourceRoot) {
    $SourceRoot = Resolve-SoundSpectrSourceRoot -InstallerRoot $InstallerRoot
}
if (-not $OutputDir) {
    $OutputDir = Join-Path $InstallerRoot "output\app"
}
$BuildDir = Join-Path $InstallerRoot "build\pyinstaller"
$DistDir = Join-Path $InstallerRoot "dist"

if (-not $PythonExe) {
    $candidate = Join-Path $SourceRoot ".venv\Scripts\python.exe"
    if (Test-Path $candidate) { $PythonExe = $candidate }
    else { $PythonExe = "python" }
}

if (-not (Test-Path $SourceRoot)) {
    throw "Source not found: $SourceRoot"
}

Write-Host "==> Using Python: $PythonExe"
Write-Host "==> Source:       $SourceRoot"

& $PythonExe -m pip install --upgrade pip pyinstaller | Out-Host
if ($LASTEXITCODE -ne 0) { throw "pip install pyinstaller failed" }

if (Test-Path $BuildDir) { Remove-Item -Recurse -Force $BuildDir }
if (Test-Path $DistDir)  { Remove-Item -Recurse -Force $DistDir }
New-Item -ItemType Directory -Force -Path $BuildDir | Out-Null

$specPath = Join-Path $InstallerRoot "soundspectranalyse_orchestrator.spec"
$specText = Get-Content -Raw -Path $specPath
$patchedSpec = Join-Path $BuildDir "soundspectranalyse_orchestrator.patched.spec"
$launcher = Join-Path $InstallerRoot "launcher_orchestrator.py"
$header = @"
# Auto-generated by Build-PyInstaller.ps1
SOURCE_ROOT = r'$($SourceRoot.Replace("'", "''"))'
LAUNCHER_SCRIPT = r'$($launcher.Replace("'", "''"))'
"@
Set-Content -Path $patchedSpec -Value ($header + "`n" + $specText) -Encoding UTF8

Push-Location $InstallerRoot
try {
    & $PythonExe -m PyInstaller `
        --noconfirm `
        --clean `
        --distpath $DistDir `
        --workpath $BuildDir `
        $patchedSpec
    if ($LASTEXITCODE -ne 0) { throw "PyInstaller failed (exit $LASTEXITCODE)" }
}
finally {
    Pop-Location
}

$built = Join-Path $DistDir "SoundSpectrAnalyse"
if (-not (Test-Path $built)) {
    throw "Expected output folder missing: $built"
}

if (Test-Path $OutputDir) { Remove-Item -Recurse -Force $OutputDir }
New-Item -ItemType Directory -Force -Path (Split-Path $OutputDir -Parent) | Out-Null
Copy-Item -Recurse -Force $built $OutputDir

$readme = @"
SoundSpectrAnalyse (portable build)
===================================

Run: SoundSpectrAnalyse Orchestrator.exe

Optional: install FFmpeg and add it to PATH for some audio formats (MP3, etc.).

Documentation: see the project README on GitHub (LuisMRaimundo/SoundSpectrAnalyse).
"@
Set-Content -Path (Join-Path $OutputDir "README.txt") -Value $readme -Encoding UTF8

$installCmd = Join-Path $InstallerRoot "Install-SoundSpectrAnalyse.cmd"
if (Test-Path $installCmd) {
    Copy-Item -Force $installCmd (Join-Path $OutputDir "Install-SoundSpectrAnalyse.cmd")
}

Write-Host ""
Write-Host "SUCCESS: Portable app at:"
Write-Host "  $OutputDir"
Write-Host ""
